services:
  fileupload-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: js-fileserver
    volumes:
      - ./images:/app/file
    ports:
      - "8020:3000"
    environment:
      - NODE_ENV=production